### ISSUE TITLE
Simplify editing the algo, plugging in other data sources

### ISSUE THREAD

**Issue by seichris** [kontext-app/roadmap#7]
## User story

As a user I want to edit the sorting algo, to customize my feed.

For news: Think a crypto version of https://feedly.com/

## Solution

Simply editing the algo with vars from Twitter.

---

### Possible input for our API

- Login with Twitter, to import your relation to the influencer accounts ([issue](https://github.com/kontext-app/roadmap/issues/16))
- More input from Hive.one api
- Like & comments from Twitter API ([issue](https://github.com/kontext-app/kontext-monorepo/issues/23))
- Content other than shared links from Twitter API ([issue](https://github.com/kontext-app/kontext-monorepo/issues/21))
- Databases other than Twitter. Eg. IMDB for movies ([issue](https://github.com/kontext-app/kontext-monorepo/issues/22))

### Possible in-between processing

- chatGPT, for prototyping algorithms. Eg. Asking it for movie recommends

---

## Tasks

- [ ] Change file setup in [twitter feeder](https://github.com/kontext-app/kontext-monorepo/tree/main/apps/twitter-feeder)
- [ ] Separate the algo vars into a config file
- [ ] And the algo logic file into its own file
- [ ] Write docs

**Comment by seichris** [comment]
### Possible input for our API

- Login with Twitter, to import your relation to the influencer accounts ([issue](https://github.com/kontext-app/roadmap/issues/16))
- More input from Hive.one api
- Like & comments from Twitter API ([issue](https://github.com/kontext-app/kontext-monorepo/issues/23))
- Content other than shared links from Twitter API ([issue](https://github.com/kontext-app/kontext-monorepo/issues/21))
- Databases other than Twitter. Eg. IMDB for movies ([issue](https://github.com/kontext-app/kontext-monorepo/issues/22))


### Possible in-between processing

- chatGPT, for prototyping algorithms. Eg. Asking it for movie recommends

**Comment by seichris** [comment]
Design ideas for algo filters:

![image](https://user-images.githubusercontent.com/25006584/220270284-d5542072-0222-4ecb-8598-bd2c55a3b57f.png)
